##########
# Digital Dramaturgy - Shakespeare Edition
# Tool for annotating/editing/publishing Shakespeare plays using Static Web Technologies
# https://github.com/thecdil/digitaldramaturgy
##########

##########
# Play SETTINGS
# Google sheets link or relative link to CSV file in the repository
# romeo and juliet play: https://docs.google.com/spreadsheets/d/e/2PACX-1vTqThHhW7kX9GoT37IB8xYUEB4K74gkSBtP9Lri58QelNVTSExuEhzGQZclCFo7hYAUKDOufvCCrjyI/pub?gid=404955959&single=true&output=csv
# midsummer play: https://docs.google.com/spreadsheets/d/e/2PACX-1vT4-hSjZe4pN0R2-fzmNyc_yrE355W1RgOBmYJ4PF-Lsyo1bKpWVKgwYqGOxGnMvvV41__J66Yjyxa1/pub?gid=651170933&single=true&output=csv
# henry v play: https://docs.google.com/spreadsheets/d/e/2PACX-1vTiBb7vwlfPv0Y1JEtAUkecHtgkmPT0lHgSvuWhKyhUYfJPAaEtNxYtfDEkxmaiJ1rPeJxu41_9WAwf/pub?gid=0&single=true&output=csv
# Hamlet play: https://docs.google.com/spreadsheets/d/e/2PACX-1vSF_02H9gFgKVe3t9-SdB-R2FCP5NXO-1W46JGBhsFA55-X6bQyr3cm-1K-1zAEf1RlA-ALaVFZTY9j/pub?output=csv
# A Comedy of Errors
play: https://docs.google.com/spreadsheets/d/e/2PACX-1vT4-hSjZe4pN0R2-fzmNyc_yrE355W1RgOBmYJ4PF-Lsyo1bKpWVKgwYqGOxGnMvvV41__J66Yjyxa1/pub?output=csv


##########
# Site SETTINGS
# Site
title: A Midsummer Night's Dream
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "a collaborative annotation of "
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: dcnb



##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
# baseurl: /dramabase
# location of code, the full url to your github repository
source-code: https://github.com/dcnb/dramabase

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
# You only need to fill this out if you are using the CollectionBuilder features also built into this tool, i.e. if you are connecting your annotations and interpretations to a digital collection of objects
metadata: demo-metadata 

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
